compatibility_date = "2023-05-18"

[[d1_databases]]
binding = 'DB' # available at env.DB
database_name = 'wanderer-moe'
database_id = 'df7af4d9-3546-42d2-bf0d-8376091a7875'
preview_database_id = 'df7af4d9-3546-42d2-bf0d-8376091a7875'